title: Project Portfolio
email: parkjinny6@gmail.com
description: >-
  Showcasing all of the projects
github_username: JKP43

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:collection/:name/